---
title: "MalReBay"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MalReBay}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style>
p.caption {
font-size: 0.85em;
font-style: italic;
color: grey
}
</style>


```{r setup, include = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    collapse = TRUE,
    comment = "#>"
)
```


```{r load-packages}
library(MalReBay)
library(future)
library(dplyr)
```

```{r define-inputs}
# Input Excel file containing cleaned TES genotype data
input_file <- system.file("extdata", "Angola_2021_TES_7NMS.xlsx", 
                          package = "MalReBay")

imported_data <- MalReBay:::import_data(filepath = input_file)

# MCMC configuration
mcmc_params <- list(
  n_chains = 4,
  chunk_size = 2000,
  max_iterations = 5000,
  burn_in_frac = 0.25,
  record_hidden_alleles = FALSE 
)

# Output folder
output_dir <- file.path(tempdir(), "infection_classification_results")
if (!dir.exists(output_dir)) dir.create(output_dir)
```

# Run the classification

```{r run-analysis}
plan(multisession, workers = mcmc_params$n_chains)

# Run the full pipeline
final_summary <- classify_infections(
  input_filepath = input_file, 
  mcmc_config        = mcmc_params,
  output_folder      = output_dir
)

plan(sequential)
```


```{r view-results}
# Ensure the Probability column is numeric for plotting
final_summary$Probability <- as.numeric(as.character(final_summary$Probability))

knitr::kable(head(final_summary), caption = "Top rows of the MCMC classification summary.")

# Histogram of posterior probabilities
graphics::hist(final_summary$Probability, breaks = 10,
     main = "Posterior Probability of Recrudescence",
     xlab = "Probability")
```


# Run the match-counting function to produce a comparison table for Bayesian and match-counting results
```{r}
match_results_df <- MalReBay:::perform_match_counting(
  genotypedata_latefailures = imported_data$late_failures, 
  marker_info = imported_data$marker_info
)

mcmc_summary_for_merge <- final_summary[, c("Sample.ID", "Probability")]
colnames(mcmc_summary_for_merge) <- c("Sample.ID", "Prob_Recrudescence")

alleles_with_patient_id <- mutate(
  imported_data$late_failures, 
  Patient.ID = gsub(" (Day 0|Day Failure)$", "", Sample.ID)
)

final_table <- left_join(
  alleles_with_patient_id, 
  match_results_df, 
  by = c("Patient.ID" = "Sample.ID")
)

final_table <- left_join(
  final_table, 
  mcmc_summary_for_merge, 
  by = c("Patient.ID" = "Sample.ID")
)

final_table_sorted <- arrange(final_table, Patient.ID, Sample.ID)

knitr::kable(
  head(final_table_sorted[, 1:10]), 
  caption = "Snapshot of the final combined data table."
)
```

