// Generated by rstantools.  Do not edit by hand.

/*
    MalReBay is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MalReBay is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with MalReBay.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_malrebay_ampseq_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 153> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 75, column 2 to column 36)",
  " (in 'string', line 76, column 2 to column 32)",
  " (in 'string', line 77, column 2 to column 35)",
  " (in 'string', line 78, column 2 to column 31)",
  " (in 'string', line 81, column 2 to column 34)",
  " (in 'string', line 83, column 2 to column 38)",
  " (in 'string', line 84, column 2 to column 44)",
  " (in 'string', line 85, column 2 to column 44)",
  " (in 'string', line 86, column 2 to column 44)",
  " (in 'string', line 89, column 2 to column 20)",
  " (in 'string', line 146, column 2 to column 42)",
  " (in 'string', line 82, column 17 to column 52)",
  " (in 'string', line 82, column 2 to column 52)",
  " (in 'string', line 91, column 4 to column 19)",
  " (in 'string', line 93, column 71 to column 80)",
  " (in 'string', line 93, column 6 to column 80)",
  " (in 'string', line 94, column 6 to column 33)",
  " (in 'string', line 95, column 6 to column 28)",
  " (in 'string', line 97, column 8 to column 39)",
  " (in 'string', line 98, column 50 to column 59)",
  " (in 'string', line 98, column 8 to column 59)",
  " (in 'string', line 109, column 12 to column 68)",
  " (in 'string', line 110, column 12 to line 111, column 58)",
  " (in 'string', line 106, column 17 to line 112, column 11)",
  " (in 'string', line 105, column 12 to column 59)",
  " (in 'string', line 103, column 41 to line 106, column 11)",
  " (in 'string', line 103, column 10 to line 112, column 11)",
  " (in 'string', line 102, column 15 to line 113, column 9)",
  " (in 'string', line 101, column 10 to column 30)",
  " (in 'string', line 99, column 39 to line 102, column 9)",
  " (in 'string', line 99, column 8 to line 113, column 9)",
  " (in 'string', line 96, column 31 to line 114, column 7)",
  " (in 'string', line 96, column 6 to line 114, column 7)",
  " (in 'string', line 116, column 8 to line 118, column 64)",
  " (in 'string', line 115, column 36 to line 119, column 7)",
  " (in 'string', line 115, column 6 to line 119, column 7)",
  " (in 'string', line 92, column 19 to line 120, column 5)",
  " (in 'string', line 92, column 4 to line 120, column 5)",
  " (in 'string', line 121, column 4 to column 21)",
  " (in 'string', line 90, column 17 to line 122, column 3)",
  " (in 'string', line 90, column 2 to line 122, column 3)",
  " (in 'string', line 129, column 2 to column 27)",
  " (in 'string', line 130, column 2 to column 27)",
  " (in 'string', line 131, column 2 to column 27)",
  " (in 'string', line 133, column 11 to column 16)",
  " (in 'string', line 133, column 4 to column 49)",
  " (in 'string', line 134, column 22 to column 37)",
  " (in 'string', line 134, column 4 to column 37)",
  " (in 'string', line 135, column 4 to column 44)",
  " (in 'string', line 136, column 4 to column 48)",
  " (in 'string', line 132, column 17 to line 137, column 3)",
  " (in 'string', line 132, column 2 to line 137, column 3)",
  " (in 'string', line 140, column 4 to column 43)",
  " (in 'string', line 139, column 2 to line 140, column 43)",
  " (in 'string', line 6, column 2 to column 17)",
  " (in 'string', line 7, column 2 to column 17)",
  " (in 'string', line 8, column 2 to column 22)",
  " (in 'string', line 9, column 2 to column 21)",
  " (in 'string', line 10, column 8 to column 9)",
  " (in 'string', line 10, column 2 to column 26)",
  " (in 'string', line 11, column 8 to column 9)",
  " (in 'string', line 11, column 11 to column 12)",
  " (in 'string', line 11, column 2 to column 32)",
  " (in 'string', line 12, column 8 to column 9)",
  " (in 'string', line 12, column 11 to column 12)",
  " (in 'string', line 12, column 2 to column 32)",
  " (in 'string', line 13, column 8 to column 9)",
  " (in 'string', line 13, column 11 to column 19)",
  " (in 'string', line 13, column 2 to column 43)",
  " (in 'string', line 14, column 8 to column 9)",
  " (in 'string', line 14, column 11 to column 19)",
  " (in 'string', line 14, column 2 to column 43)",
  " (in 'string', line 15, column 8 to column 9)",
  " (in 'string', line 15, column 11 to column 19)",
  " (in 'string', line 15, column 2 to column 51)",
  " (in 'string', line 16, column 8 to column 9)",
  " (in 'string', line 16, column 11 to column 19)",
  " (in 'string', line 16, column 2 to column 51)",
  " (in 'string', line 17, column 8 to column 9)",
  " (in 'string', line 17, column 11 to column 12)",
  " (in 'string', line 17, column 2 to column 47)",
  " (in 'string', line 18, column 8 to column 9)",
  " (in 'string', line 18, column 11 to column 16)",
  " (in 'string', line 18, column 2 to column 49)",
  " (in 'string', line 24, column 8 to column 9)",
  " (in 'string', line 24, column 11 to column 12)",
  " (in 'string', line 24, column 2 to column 54)",
  " (in 'string', line 25, column 8 to column 9)",
  " (in 'string', line 25, column 11 to column 12)",
  " (in 'string', line 25, column 2 to column 54)",
  " (in 'string', line 26, column 8 to column 9)",
  " (in 'string', line 26, column 11 to column 12)",
  " (in 'string', line 26, column 2 to column 54)",
  " (in 'string', line 27, column 8 to column 9)",
  " (in 'string', line 27, column 11 to column 12)",
  " (in 'string', line 27, column 2 to column 54)",
  " (in 'string', line 30, column 8 to column 9)",
  " (in 'string', line 30, column 11 to column 19)",
  " (in 'string', line 30, column 2 to column 68)",
  " (in 'string', line 34, column 8 to column 17)",
  " (in 'string', line 33, column 6 to line 34, column 17)",
  " (in 'string', line 35, column 6 to column 33)",
  " (in 'string', line 38, column 8 to column 39)",
  " (in 'string', line 39, column 50 to column 59)",
  " (in 'string', line 39, column 8 to column 59)",
  " (in 'string', line 40, column 8 to column 22)",
  " (in 'string', line 43, column 12 to column 22)",
  " (in 'string', line 43, column 23 to column 29)",
  " (in 'string', line 42, column 72 to line 44, column 11)",
  " (in 'string', line 42, column 10 to line 44, column 11)",
  " (in 'string', line 41, column 33 to line 45, column 9)",
  " (in 'string', line 41, column 8 to line 45, column 9)",
  " (in 'string', line 46, column 20 to column 41)",
  " (in 'string', line 46, column 8 to column 41)",
  " (in 'string', line 37, column 31 to line 47, column 7)",
  " (in 'string', line 37, column 6 to line 47, column 7)",
  " (in 'string', line 50, column 41 to column 61)",
  " (in 'string', line 50, column 62 to column 80)",
  " (in 'string', line 50, column 39 to column 82)",
  " (in 'string', line 50, column 8 to column 82)",
  " (in 'string', line 49, column 31 to line 51, column 7)",
  " (in 'string', line 49, column 6 to line 51, column 7)",
  " (in 'string', line 53, column 39 to column 57)",
  " (in 'string', line 53, column 8 to column 57)",
  " (in 'string', line 52, column 31 to line 54, column 7)",
  " (in 'string', line 52, column 6 to line 54, column 7)",
  " (in 'string', line 57, column 8 to column 39)",
  " (in 'string', line 58, column 50 to column 59)",
  " (in 'string', line 58, column 8 to column 59)",
  " (in 'string', line 59, column 8 to column 34)",
  " (in 'string', line 61, column 10 to column 24)",
  " (in 'string', line 64, column 14 to column 24)",
  " (in 'string', line 64, column 25 to column 31)",
  " (in 'string', line 63, column 74 to line 65, column 13)",
  " (in 'string', line 63, column 12 to line 65, column 13)",
  " (in 'string', line 62, column 35 to line 66, column 11)",
  " (in 'string', line 62, column 10 to line 66, column 11)",
  " (in 'string', line 67, column 10 to column 44)",
  " (in 'string', line 60, column 39 to line 68, column 9)",
  " (in 'string', line 60, column 8 to line 68, column 9)",
  " (in 'string', line 56, column 31 to line 70, column 7)",
  " (in 'string', line 56, column 6 to line 70, column 7)",
  " (in 'string', line 32, column 19 to line 71, column 5)",
  " (in 'string', line 32, column 4 to line 71, column 5)",
  " (in 'string', line 31, column 17 to line 72, column 3)",
  " (in 'string', line 31, column 2 to line 72, column 3)",
  " (in 'string', line 78, column 8 to column 9)",
  " (in 'string', line 78, column 19 to column 24)",
  " (in 'string', line 81, column 8 to column 9)",
  " (in 'string', line 81, column 18 to column 23)",
  " (in 'string', line 89, column 9 to column 10)",
  " (in 'string', line 146, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_malrebay_ampseq_model final : public model_base_crtp<model_malrebay_ampseq_model> {
private:
  int N;
  int J;
  int maxMOI;
  int max_K;
  std::vector<int> K;
  std::vector<std::vector<int>> MOI0;
  std::vector<std::vector<int>> MOIf;
  std::vector<std::vector<int>> recoded0;
  std::vector<std::vector<int>> recodedf;
  std::vector<std::vector<int>> hidden0;
  std::vector<std::vector<int>> hiddenf;
  std::vector<std::vector<int>> comparable;
  std::vector<std::vector<int>> additional_counts;
  std::vector<std::vector<int>> td_n_lost;
  std::vector<std::vector<int>> td_m_i_0;
  std::vector<std::vector<int>> td_m_i;
  std::vector<std::vector<int>> td_n_alleles_f;
  std::vector<std::vector<int>> td_has_match;
public:
  ~model_malrebay_ampseq_model() {}
  model_malrebay_ampseq_model(stan::io::var_context& context__, unsigned int
                              random_seed__ = 0, std::ostream*
                              pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_malrebay_ampseq_model_namespace::model_malrebay_ampseq_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 55;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 55;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 55;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 56;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 56;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "maxMOI", "int",
        std::vector<size_t>{});
      maxMOI = std::numeric_limits<int>::min();
      current_statement__ = 57;
      maxMOI = context__.vals_i("maxMOI")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "maxMOI", maxMOI, 1);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "max_K", "int",
        std::vector<size_t>{});
      max_K = std::numeric_limits<int>::min();
      current_statement__ = 58;
      max_K = context__.vals_i("max_K")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "max_K", max_K, 1);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("K", "J", J);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{static_cast<size_t>(J)});
      K = std::vector<int>(J, std::numeric_limits<int>::min());
      current_statement__ = 60;
      K = context__.vals_i("K");
      current_statement__ = 60;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("MOI0", "N", N);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("MOI0", "J", J);
      current_statement__ = 63;
      context__.validate_dims("data initialization", "MOI0", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(J)});
      MOI0 = std::vector<std::vector<int>>(N,
               std::vector<int>(J, std::numeric_limits<int>::min()));
      {
        std::vector<int> MOI0_flat__;
        current_statement__ = 63;
        MOI0_flat__ = context__.vals_i("MOI0");
        current_statement__ = 63;
        pos__ = 1;
        current_statement__ = 63;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 63;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 63;
            stan::model::assign(MOI0, MOI0_flat__[(pos__ - 1)],
              "assigning variable MOI0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 63;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 63;
      stan::math::check_greater_or_equal(function__, "MOI0", MOI0, 0);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("MOIf", "N", N);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("MOIf", "J", J);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "MOIf", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(J)});
      MOIf = std::vector<std::vector<int>>(N,
               std::vector<int>(J, std::numeric_limits<int>::min()));
      {
        std::vector<int> MOIf_flat__;
        current_statement__ = 66;
        MOIf_flat__ = context__.vals_i("MOIf");
        current_statement__ = 66;
        pos__ = 1;
        current_statement__ = 66;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 66;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 66;
            stan::model::assign(MOIf, MOIf_flat__[(pos__ - 1)],
              "assigning variable MOIf", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 66;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 66;
      stan::math::check_greater_or_equal(function__, "MOIf", MOIf, 0);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("recoded0", "N", N);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("recoded0", "J * maxMOI", (J *
        maxMOI));
      current_statement__ = 69;
      context__.validate_dims("data initialization", "recoded0", "int",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>((J * maxMOI))});
      recoded0 = std::vector<std::vector<int>>(N,
                   std::vector<int>((J * maxMOI),
                     std::numeric_limits<int>::min()));
      {
        std::vector<int> recoded0_flat__;
        current_statement__ = 69;
        recoded0_flat__ = context__.vals_i("recoded0");
        current_statement__ = 69;
        pos__ = 1;
        current_statement__ = 69;
        for (int sym1__ = 1; sym1__ <= (J * maxMOI); ++sym1__) {
          current_statement__ = 69;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 69;
            stan::model::assign(recoded0, recoded0_flat__[(pos__ - 1)],
              "assigning variable recoded0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 69;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 69;
      stan::math::check_greater_or_equal(function__, "recoded0", recoded0, 0);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("recodedf", "N", N);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("recodedf", "J * maxMOI", (J *
        maxMOI));
      current_statement__ = 72;
      context__.validate_dims("data initialization", "recodedf", "int",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>((J * maxMOI))});
      recodedf = std::vector<std::vector<int>>(N,
                   std::vector<int>((J * maxMOI),
                     std::numeric_limits<int>::min()));
      {
        std::vector<int> recodedf_flat__;
        current_statement__ = 72;
        recodedf_flat__ = context__.vals_i("recodedf");
        current_statement__ = 72;
        pos__ = 1;
        current_statement__ = 72;
        for (int sym1__ = 1; sym1__ <= (J * maxMOI); ++sym1__) {
          current_statement__ = 72;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 72;
            stan::model::assign(recodedf, recodedf_flat__[(pos__ - 1)],
              "assigning variable recodedf", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 72;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 72;
      stan::math::check_greater_or_equal(function__, "recodedf", recodedf, 0);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("hidden0", "N", N);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("hidden0", "J * maxMOI", (J *
        maxMOI));
      current_statement__ = 75;
      context__.validate_dims("data initialization", "hidden0", "int",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>((J * maxMOI))});
      hidden0 = std::vector<std::vector<int>>(N,
                  std::vector<int>((J * maxMOI),
                    std::numeric_limits<int>::min()));
      {
        std::vector<int> hidden0_flat__;
        current_statement__ = 75;
        hidden0_flat__ = context__.vals_i("hidden0");
        current_statement__ = 75;
        pos__ = 1;
        current_statement__ = 75;
        for (int sym1__ = 1; sym1__ <= (J * maxMOI); ++sym1__) {
          current_statement__ = 75;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 75;
            stan::model::assign(hidden0, hidden0_flat__[(pos__ - 1)],
              "assigning variable hidden0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 75;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 75;
      stan::math::check_greater_or_equal(function__, "hidden0", hidden0, 0);
      current_statement__ = 75;
      stan::math::check_less_or_equal(function__, "hidden0", hidden0, 1);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("hiddenf", "N", N);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("hiddenf", "J * maxMOI", (J *
        maxMOI));
      current_statement__ = 78;
      context__.validate_dims("data initialization", "hiddenf", "int",
        std::vector<size_t>{static_cast<size_t>(N),
          static_cast<size_t>((J * maxMOI))});
      hiddenf = std::vector<std::vector<int>>(N,
                  std::vector<int>((J * maxMOI),
                    std::numeric_limits<int>::min()));
      {
        std::vector<int> hiddenf_flat__;
        current_statement__ = 78;
        hiddenf_flat__ = context__.vals_i("hiddenf");
        current_statement__ = 78;
        pos__ = 1;
        current_statement__ = 78;
        for (int sym1__ = 1; sym1__ <= (J * maxMOI); ++sym1__) {
          current_statement__ = 78;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 78;
            stan::model::assign(hiddenf, hiddenf_flat__[(pos__ - 1)],
              "assigning variable hiddenf", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 78;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 78;
      stan::math::check_greater_or_equal(function__, "hiddenf", hiddenf, 0);
      current_statement__ = 78;
      stan::math::check_less_or_equal(function__, "hiddenf", hiddenf, 1);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("comparable", "N", N);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("comparable", "J", J);
      current_statement__ = 81;
      context__.validate_dims("data initialization", "comparable", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(J)});
      comparable = std::vector<std::vector<int>>(N,
                     std::vector<int>(J, std::numeric_limits<int>::min()));
      {
        std::vector<int> comparable_flat__;
        current_statement__ = 81;
        comparable_flat__ = context__.vals_i("comparable");
        current_statement__ = 81;
        pos__ = 1;
        current_statement__ = 81;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 81;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 81;
            stan::model::assign(comparable, comparable_flat__[(pos__ - 1)],
              "assigning variable comparable",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 81;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 81;
      stan::math::check_greater_or_equal(function__, "comparable",
        comparable, 0);
      current_statement__ = 81;
      stan::math::check_less_or_equal(function__, "comparable", comparable, 1);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("additional_counts", "J", J);
      current_statement__ = 83;
      stan::math::validate_non_negative_index("additional_counts", "max_K",
        max_K);
      current_statement__ = 84;
      context__.validate_dims("data initialization", "additional_counts",
        "int",
        std::vector<size_t>{static_cast<size_t>(J),
          static_cast<size_t>(max_K)});
      additional_counts = std::vector<std::vector<int>>(J,
                            std::vector<int>(max_K,
                              std::numeric_limits<int>::min()));
      {
        std::vector<int> additional_counts_flat__;
        current_statement__ = 84;
        additional_counts_flat__ = context__.vals_i("additional_counts");
        current_statement__ = 84;
        pos__ = 1;
        current_statement__ = 84;
        for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
          current_statement__ = 84;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 84;
            stan::model::assign(additional_counts,
              additional_counts_flat__[(pos__ - 1)],
              "assigning variable additional_counts",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 84;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 84;
      stan::math::check_greater_or_equal(function__, "additional_counts",
        additional_counts, 0);
      current_statement__ = 85;
      stan::math::validate_non_negative_index("td_n_lost", "N", N);
      current_statement__ = 86;
      stan::math::validate_non_negative_index("td_n_lost", "J", J);
      current_statement__ = 87;
      td_n_lost = std::vector<std::vector<int>>(N,
                    std::vector<int>(J, std::numeric_limits<int>::min()));
      current_statement__ = 87;
      stan::model::assign(td_n_lost, stan::math::rep_array(0, N, J),
        "assigning variable td_n_lost");
      current_statement__ = 88;
      stan::math::validate_non_negative_index("td_m_i_0", "N", N);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("td_m_i_0", "J", J);
      current_statement__ = 90;
      td_m_i_0 = std::vector<std::vector<int>>(N,
                   std::vector<int>(J, std::numeric_limits<int>::min()));
      current_statement__ = 90;
      stan::model::assign(td_m_i_0, stan::math::rep_array(0, N, J),
        "assigning variable td_m_i_0");
      current_statement__ = 91;
      stan::math::validate_non_negative_index("td_m_i", "N", N);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("td_m_i", "J", J);
      current_statement__ = 93;
      td_m_i = std::vector<std::vector<int>>(N,
                 std::vector<int>(J, std::numeric_limits<int>::min()));
      current_statement__ = 93;
      stan::model::assign(td_m_i, stan::math::rep_array(0, N, J),
        "assigning variable td_m_i");
      current_statement__ = 94;
      stan::math::validate_non_negative_index("td_n_alleles_f", "N", N);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("td_n_alleles_f", "J", J);
      current_statement__ = 96;
      td_n_alleles_f = std::vector<std::vector<int>>(N,
                         std::vector<int>(J, std::numeric_limits<int>::min()));
      current_statement__ = 96;
      stan::model::assign(td_n_alleles_f, stan::math::rep_array(0, N, J),
        "assigning variable td_n_alleles_f");
      current_statement__ = 97;
      stan::math::validate_non_negative_index("td_has_match", "N", N);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("td_has_match", "J * maxMOI",
        (J * maxMOI));
      current_statement__ = 99;
      td_has_match = std::vector<std::vector<int>>(N,
                       std::vector<int>((J * maxMOI),
                         std::numeric_limits<int>::min()));
      current_statement__ = 99;
      stan::model::assign(td_has_match,
        stan::math::rep_array(0, N, (J * maxMOI)),
        "assigning variable td_has_match");
      current_statement__ = 146;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 144;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 101;
          if ((stan::math::primitive_value(
                 (stan::math::primitive_value(
                    stan::math::logical_eq(
                      stan::model::rvalue(comparable, "comparable",
                        stan::model::index_uni(i), stan::model::index_uni(j)),
                      0)) ||
                 stan::math::primitive_value(
                   stan::math::logical_eq(
                     stan::model::rvalue(MOI0, "MOI0",
                       stan::model::index_uni(i), stan::model::index_uni(j)),
                     0))))
              ||
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(MOIf, "MOIf",
                    stan::model::index_uni(i), stan::model::index_uni(j)), 0)))) {
            continue;
          }
          int off = std::numeric_limits<int>::min();
          current_statement__ = 102;
          off = ((j - 1) * maxMOI);
          current_statement__ = 116;
          for (int a0 = 1; a0 <=
               stan::model::rvalue(MOI0, "MOI0", stan::model::index_uni(i),
                 stan::model::index_uni(j)); ++a0) {
            int k0 = std::numeric_limits<int>::min();
            current_statement__ = 103;
            k0 = stan::model::rvalue(recoded0, "recoded0",
                   stan::model::index_uni(i),
                   stan::model::index_uni((off + a0)));
            current_statement__ = 105;
            if ((stan::math::primitive_value(stan::math::logical_eq(k0, 0))
                ||
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(hidden0, "hidden0",
                      stan::model::index_uni(i),
                      stan::model::index_uni((off + a0))), 1)))) {
              continue;
            }
            int found = std::numeric_limits<int>::min();
            current_statement__ = 106;
            found = 0;
            current_statement__ = 112;
            for (int af = 1; af <=
                 stan::model::rvalue(MOIf, "MOIf", stan::model::index_uni(i),
                   stan::model::index_uni(j)); ++af) {
              current_statement__ = 110;
              if ((stan::math::primitive_value(
                     stan::math::logical_eq(
                       stan::model::rvalue(recodedf, "recodedf",
                         stan::model::index_uni(i),
                         stan::model::index_uni((off + af))), k0))
                  &&
                  stan::math::primitive_value(
                    stan::math::logical_eq(
                      stan::model::rvalue(hiddenf, "hiddenf",
                        stan::model::index_uni(i),
                        stan::model::index_uni((off + af))), 0)))) {
                current_statement__ = 107;
                found = 1;
                break;
              }
            }
            current_statement__ = 114;
            if (stan::math::logical_negation(found)) {
              current_statement__ = 113;
              stan::model::assign(td_n_lost,
                (stan::model::rvalue(td_n_lost, "td_n_lost",
                   stan::model::index_uni(i), stan::model::index_uni(j)) +
                1), "assigning variable td_n_lost",
                stan::model::index_uni(i), stan::model::index_uni(j));
            }
          }
          current_statement__ = 122;
          for (int a0 = 1; a0 <=
               stan::model::rvalue(MOI0, "MOI0", stan::model::index_uni(i),
                 stan::model::index_uni(j)); ++a0) {
            current_statement__ = 120;
            if (stan::math::logical_eq(
                  stan::model::rvalue(hidden0, "hidden0",
                    stan::model::index_uni(i),
                    stan::model::index_uni((off + a0))), 1)) {
              current_statement__ = 117;
              stan::model::assign(td_m_i_0,
                (stan::model::rvalue(td_m_i_0, "td_m_i_0",
                   stan::model::index_uni(i), stan::model::index_uni(j)) +
                1), "assigning variable td_m_i_0", stan::model::index_uni(i),
                stan::model::index_uni(j));
              current_statement__ = 118;
              stan::model::assign(td_m_i,
                (stan::model::rvalue(td_m_i, "td_m_i",
                   stan::model::index_uni(i), stan::model::index_uni(j)) +
                1), "assigning variable td_m_i", stan::model::index_uni(i),
                stan::model::index_uni(j));
            }
          }
          current_statement__ = 126;
          for (int af = 1; af <=
               stan::model::rvalue(MOIf, "MOIf", stan::model::index_uni(i),
                 stan::model::index_uni(j)); ++af) {
            current_statement__ = 124;
            if (stan::math::logical_eq(
                  stan::model::rvalue(hiddenf, "hiddenf",
                    stan::model::index_uni(i),
                    stan::model::index_uni((off + af))), 1)) {
              current_statement__ = 123;
              stan::model::assign(td_m_i,
                (stan::model::rvalue(td_m_i, "td_m_i",
                   stan::model::index_uni(i), stan::model::index_uni(j)) +
                1), "assigning variable td_m_i", stan::model::index_uni(i),
                stan::model::index_uni(j));
            }
          }
          current_statement__ = 142;
          for (int af = 1; af <=
               stan::model::rvalue(MOIf, "MOIf", stan::model::index_uni(i),
                 stan::model::index_uni(j)); ++af) {
            int kf = std::numeric_limits<int>::min();
            current_statement__ = 127;
            kf = stan::model::rvalue(recodedf, "recodedf",
                   stan::model::index_uni(i),
                   stan::model::index_uni((off + af)));
            current_statement__ = 129;
            if ((stan::math::primitive_value(stan::math::logical_eq(kf, 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(hiddenf, "hiddenf",
                      stan::model::index_uni(i),
                      stan::model::index_uni((off + af))), 0)))) {
              continue;
            }
            current_statement__ = 130;
            stan::model::assign(td_n_alleles_f,
              (stan::model::rvalue(td_n_alleles_f, "td_n_alleles_f",
                 stan::model::index_uni(i), stan::model::index_uni(j)) + 1),
              "assigning variable td_n_alleles_f", stan::model::index_uni(i),
              stan::model::index_uni(j));
            current_statement__ = 140;
            if (stan::math::logical_eq(
                  stan::model::rvalue(hiddenf, "hiddenf",
                    stan::model::index_uni(i),
                    stan::model::index_uni((off + af))), 0)) {
              int match = std::numeric_limits<int>::min();
              current_statement__ = 131;
              match = 0;
              current_statement__ = 137;
              for (int a0 = 1; a0 <=
                   stan::model::rvalue(MOI0, "MOI0",
                     stan::model::index_uni(i), stan::model::index_uni(j)); ++a0) {
                current_statement__ = 135;
                if ((stan::math::primitive_value(
                       stan::math::logical_eq(
                         stan::model::rvalue(recoded0, "recoded0",
                           stan::model::index_uni(i),
                           stan::model::index_uni((off + a0))), kf))
                    &&
                    stan::math::primitive_value(
                      stan::math::logical_eq(
                        stan::model::rvalue(hidden0, "hidden0",
                          stan::model::index_uni(i),
                          stan::model::index_uni((off + a0))), 0)))) {
                  current_statement__ = 132;
                  match = 1;
                  break;
                }
              }
              current_statement__ = 138;
              stan::model::assign(td_has_match, match,
                "assigning variable td_has_match", stan::model::index_uni(i),
                stan::model::index_uni((off + af)));
            }
          }
        }
      }
      current_statement__ = 147;
      stan::math::validate_non_negative_index("freq", "J", J);
      current_statement__ = 148;
      stan::math::validate_positive_index("freq", "max_K", max_K);
      current_statement__ = 149;
      stan::math::validate_non_negative_index("log_freq", "J", J);
      current_statement__ = 150;
      stan::math::validate_non_negative_index("log_freq", "max_K", max_K);
      current_statement__ = 151;
      stan::math::validate_non_negative_index("slr_vec", "N", N);
      current_statement__ = 152;
      stan::math::validate_non_negative_index("p_recrud", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + (J * (max_K - 1));
  }
  inline std::string model_name() const final {
    return "model_malrebay_ampseq_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_malrebay_ampseq_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ q_mismatch = DUMMY_VAR__;
      current_statement__ = 1;
      q_mismatch = in__.template read_constrain_lub<local_scalar_t__,
                     jacobian__>(0, 1, lp__);
      local_scalar_t__ q_loss = DUMMY_VAR__;
      current_statement__ = 2;
      q_loss = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      local_scalar_t__ q_dropout = DUMMY_VAR__;
      current_statement__ = 3;
      q_dropout = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> freq =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(J,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(max_K, DUMMY_VAR__));
      current_statement__ = 4;
      freq = in__.template read_constrain_simplex<
               std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
               jacobian__>(lp__, J, max_K);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> log_freq =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(J,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(max_K, DUMMY_VAR__));
      current_statement__ = 13;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 12;
        stan::model::assign(log_freq,
          stan::math::log(
            stan::math::add(
              stan::model::rvalue(freq, "freq", stan::model::index_uni(j)),
              1e-10)), "assigning variable log_freq",
          stan::model::index_uni(j));
      }
      local_scalar_t__ l_match = DUMMY_VAR__;
      current_statement__ = 6;
      l_match = stan::math::log1m(q_mismatch);
      local_scalar_t__ l_mismatch = DUMMY_VAR__;
      current_statement__ = 7;
      l_mismatch = stan::math::log((q_mismatch + 1e-10));
      local_scalar_t__ l_dropout = DUMMY_VAR__;
      current_statement__ = 8;
      l_dropout = stan::math::log((q_dropout + 1e-10));
      local_scalar_t__ l_loss = DUMMY_VAR__;
      current_statement__ = 9;
      l_loss = stan::math::log((q_loss + 1e-10));
      Eigen::Matrix<local_scalar_t__,-1,1> slr_vec =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 41;
      for (int i = 1; i <= N; ++i) {
        local_scalar_t__ slr = DUMMY_VAR__;
        current_statement__ = 14;
        slr = 0.0;
        current_statement__ = 38;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 16;
          if ((stan::math::primitive_value(
                 (stan::math::primitive_value(
                    stan::math::logical_eq(
                      stan::model::rvalue(comparable, "comparable",
                        stan::model::index_uni(i), stan::model::index_uni(j)),
                      0)) ||
                 stan::math::primitive_value(
                   stan::math::logical_eq(
                     stan::model::rvalue(MOI0, "MOI0",
                       stan::model::index_uni(i), stan::model::index_uni(j)),
                     0))))
              ||
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(MOIf, "MOIf",
                    stan::model::index_uni(i), stan::model::index_uni(j)), 0)))) {
            continue;
          }
          int off = std::numeric_limits<int>::min();
          current_statement__ = 17;
          off = ((j - 1) * maxMOI);
          local_scalar_t__ locus_sum_lr = DUMMY_VAR__;
          current_statement__ = 18;
          locus_sum_lr = 0;
          current_statement__ = 33;
          for (int af = 1; af <=
               stan::model::rvalue(MOIf, "MOIf", stan::model::index_uni(i),
                 stan::model::index_uni(j)); ++af) {
            int kf = std::numeric_limits<int>::min();
            current_statement__ = 19;
            kf = stan::model::rvalue(recodedf, "recodedf",
                   stan::model::index_uni(i),
                   stan::model::index_uni((off + af)));
            current_statement__ = 21;
            if ((stan::math::primitive_value(stan::math::logical_eq(kf, 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(hiddenf, "hiddenf",
                      stan::model::index_uni(i),
                      stan::model::index_uni((off + af))), 0)))) {
              continue;
            }
            current_statement__ = 31;
            if (stan::math::logical_eq(
                  stan::model::rvalue(hiddenf, "hiddenf",
                    stan::model::index_uni(i),
                    stan::model::index_uni((off + af))), 1)) {
              current_statement__ = 29;
              locus_sum_lr = (locus_sum_lr + 1.0);
            } else {
              current_statement__ = 27;
              if (stan::model::rvalue(td_has_match, "td_has_match",
                    stan::model::index_uni(i),
                    stan::model::index_uni((off + af)))) {
                current_statement__ = 25;
                locus_sum_lr = (locus_sum_lr +
                  stan::math::exp((l_match -
                    stan::model::rvalue(
                      stan::model::rvalue(log_freq, "log_freq",
                        stan::model::index_uni(j)), "log_freq[j]",
                      stan::model::index_uni(kf)))));
              } else {
                local_scalar_t__ phm = DUMMY_VAR__;
                current_statement__ = 22;
                phm = (1.0 -
                  stan::math::pow((1.0 -
                    stan::model::rvalue(
                      stan::model::rvalue(freq, "freq",
                        stan::model::index_uni(j)), "freq[j]",
                      stan::model::index_uni(kf))),
                    stan::model::rvalue(td_m_i_0, "td_m_i_0",
                      stan::model::index_uni(i), stan::model::index_uni(j))));
                current_statement__ = 23;
                locus_sum_lr = (locus_sum_lr + ((phm *
                  stan::math::exp((l_match -
                    stan::model::rvalue(
                      stan::model::rvalue(log_freq, "log_freq",
                        stan::model::index_uni(j)), "log_freq[j]",
                      stan::model::index_uni(kf)))))
                  + ((1.0 - phm) * stan::math::exp(l_mismatch))));
              }
            }
          }
          current_statement__ = 36;
          if (stan::math::logical_gt(
                stan::model::rvalue(td_n_alleles_f, "td_n_alleles_f",
                  stan::model::index_uni(i), stan::model::index_uni(j)), 0)) {
            current_statement__ = 34;
            slr = (slr +
              (((stan::model::rvalue(td_n_lost, "td_n_lost",
                   stan::model::index_uni(i), stan::model::index_uni(j))
              * l_loss) +
              (stan::model::rvalue(td_m_i, "td_m_i",
                 stan::model::index_uni(i), stan::model::index_uni(j))
              * l_dropout)) +
              stan::math::log(((locus_sum_lr /
                stan::model::rvalue(td_n_alleles_f, "td_n_alleles_f",
                  stan::model::index_uni(i), stan::model::index_uni(j))) +
                1e-10))));
          }
        }
        current_statement__ = 39;
        stan::model::assign(slr_vec, slr, "assigning variable slr_vec",
          stan::model::index_uni(i));
      }
      {
        current_statement__ = 42;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(q_mismatch, 1, 50));
        current_statement__ = 43;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(q_loss, 1, 1));
        current_statement__ = 44;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(q_dropout, 1, 50));
        current_statement__ = 52;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 45;
          stan::math::validate_non_negative_index("alpha", "max_K", max_K);
          Eigen::Matrix<local_scalar_t__,-1,1> alpha =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(max_K,
              DUMMY_VAR__);
          current_statement__ = 46;
          stan::model::assign(alpha, stan::math::rep_vector(0.1, max_K),
            "assigning variable alpha");
          current_statement__ = 48;
          for (int k = 1; k <=
               stan::model::rvalue(K, "K", stan::model::index_uni(j)); ++k) {
            current_statement__ = 47;
            stan::model::assign(alpha, 1.0, "assigning variable alpha",
              stan::model::index_uni(k));
          }
          current_statement__ = 49;
          lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(
                           stan::model::rvalue(freq, "freq",
                             stan::model::index_uni(j)), alpha));
          current_statement__ = 50;
          lp_accum__.add(stan::math::multinomial_lpmf<propto__>(
                           stan::model::rvalue(additional_counts,
                             "additional_counts", stan::model::index_uni(j)),
                           stan::model::rvalue(freq, "freq",
                             stan::model::index_uni(j))));
        }
        current_statement__ = 54;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 53;
          lp_accum__.add(stan::math::log_sum_exp(
                           stan::model::rvalue(slr_vec, "slr_vec",
                             stan::model::index_uni(i)), 0.0));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_malrebay_ampseq_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double q_mismatch = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      q_mismatch = in__.template read_constrain_lub<local_scalar_t__,
                     jacobian__>(0, 1, lp__);
      double q_loss = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      q_loss = in__.template read_constrain_lub<local_scalar_t__,
                 jacobian__>(0, 1, lp__);
      double q_dropout = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      q_dropout = in__.template read_constrain_lub<local_scalar_t__,
                    jacobian__>(0, 1, lp__);
      std::vector<Eigen::Matrix<double,-1,1>> freq =
        std::vector<Eigen::Matrix<double,-1,1>>(J,
          Eigen::Matrix<double,-1,1>::Constant(max_K,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 4;
      freq = in__.template read_constrain_simplex<
               std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
               jacobian__>(lp__, J, max_K);
      std::vector<Eigen::Matrix<double,-1,1>> log_freq =
        std::vector<Eigen::Matrix<double,-1,1>>(J,
          Eigen::Matrix<double,-1,1>::Constant(max_K,
            std::numeric_limits<double>::quiet_NaN()));
      double l_match = std::numeric_limits<double>::quiet_NaN();
      double l_mismatch = std::numeric_limits<double>::quiet_NaN();
      double l_dropout = std::numeric_limits<double>::quiet_NaN();
      double l_loss = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> slr_vec =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(q_mismatch);
      out__.write(q_loss);
      out__.write(q_dropout);
      for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          out__.write(freq[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 13;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 12;
        stan::model::assign(log_freq,
          stan::math::log(
            stan::math::add(
              stan::model::rvalue(freq, "freq", stan::model::index_uni(j)),
              1e-10)), "assigning variable log_freq",
          stan::model::index_uni(j));
      }
      current_statement__ = 6;
      l_match = stan::math::log1m(q_mismatch);
      current_statement__ = 7;
      l_mismatch = stan::math::log((q_mismatch + 1e-10));
      current_statement__ = 8;
      l_dropout = stan::math::log((q_dropout + 1e-10));
      current_statement__ = 9;
      l_loss = stan::math::log((q_loss + 1e-10));
      current_statement__ = 41;
      for (int i = 1; i <= N; ++i) {
        double slr = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 14;
        slr = 0.0;
        current_statement__ = 38;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 16;
          if ((stan::math::primitive_value(
                 (stan::math::primitive_value(
                    stan::math::logical_eq(
                      stan::model::rvalue(comparable, "comparable",
                        stan::model::index_uni(i), stan::model::index_uni(j)),
                      0)) ||
                 stan::math::primitive_value(
                   stan::math::logical_eq(
                     stan::model::rvalue(MOI0, "MOI0",
                       stan::model::index_uni(i), stan::model::index_uni(j)),
                     0))))
              ||
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(MOIf, "MOIf",
                    stan::model::index_uni(i), stan::model::index_uni(j)), 0)))) {
            continue;
          }
          int off = std::numeric_limits<int>::min();
          current_statement__ = 17;
          off = ((j - 1) * maxMOI);
          double locus_sum_lr = std::numeric_limits<double>::quiet_NaN();
          current_statement__ = 18;
          locus_sum_lr = 0;
          current_statement__ = 33;
          for (int af = 1; af <=
               stan::model::rvalue(MOIf, "MOIf", stan::model::index_uni(i),
                 stan::model::index_uni(j)); ++af) {
            int kf = std::numeric_limits<int>::min();
            current_statement__ = 19;
            kf = stan::model::rvalue(recodedf, "recodedf",
                   stan::model::index_uni(i),
                   stan::model::index_uni((off + af)));
            current_statement__ = 21;
            if ((stan::math::primitive_value(stan::math::logical_eq(kf, 0))
                &&
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::model::rvalue(hiddenf, "hiddenf",
                      stan::model::index_uni(i),
                      stan::model::index_uni((off + af))), 0)))) {
              continue;
            }
            current_statement__ = 31;
            if (stan::math::logical_eq(
                  stan::model::rvalue(hiddenf, "hiddenf",
                    stan::model::index_uni(i),
                    stan::model::index_uni((off + af))), 1)) {
              current_statement__ = 29;
              locus_sum_lr = (locus_sum_lr + 1.0);
            } else {
              current_statement__ = 27;
              if (stan::model::rvalue(td_has_match, "td_has_match",
                    stan::model::index_uni(i),
                    stan::model::index_uni((off + af)))) {
                current_statement__ = 25;
                locus_sum_lr = (locus_sum_lr +
                  stan::math::exp((l_match -
                    stan::model::rvalue(
                      stan::model::rvalue(log_freq, "log_freq",
                        stan::model::index_uni(j)), "log_freq[j]",
                      stan::model::index_uni(kf)))));
              } else {
                double phm = std::numeric_limits<double>::quiet_NaN();
                current_statement__ = 22;
                phm = (1.0 -
                  stan::math::pow((1.0 -
                    stan::model::rvalue(
                      stan::model::rvalue(freq, "freq",
                        stan::model::index_uni(j)), "freq[j]",
                      stan::model::index_uni(kf))),
                    stan::model::rvalue(td_m_i_0, "td_m_i_0",
                      stan::model::index_uni(i), stan::model::index_uni(j))));
                current_statement__ = 23;
                locus_sum_lr = (locus_sum_lr + ((phm *
                  stan::math::exp((l_match -
                    stan::model::rvalue(
                      stan::model::rvalue(log_freq, "log_freq",
                        stan::model::index_uni(j)), "log_freq[j]",
                      stan::model::index_uni(kf)))))
                  + ((1.0 - phm) * stan::math::exp(l_mismatch))));
              }
            }
          }
          current_statement__ = 36;
          if (stan::math::logical_gt(
                stan::model::rvalue(td_n_alleles_f, "td_n_alleles_f",
                  stan::model::index_uni(i), stan::model::index_uni(j)), 0)) {
            current_statement__ = 34;
            slr = (slr +
              (((stan::model::rvalue(td_n_lost, "td_n_lost",
                   stan::model::index_uni(i), stan::model::index_uni(j))
              * l_loss) +
              (stan::model::rvalue(td_m_i, "td_m_i",
                 stan::model::index_uni(i), stan::model::index_uni(j))
              * l_dropout)) +
              stan::math::log(((locus_sum_lr /
                stan::model::rvalue(td_n_alleles_f, "td_n_alleles_f",
                  stan::model::index_uni(i), stan::model::index_uni(j))) +
                1e-10))));
          }
        }
        current_statement__ = 39;
        stan::model::assign(slr_vec, slr, "assigning variable slr_vec",
          stan::model::index_uni(i));
      }
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            out__.write(log_freq[(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
        out__.write(l_match);
        out__.write(l_mismatch);
        out__.write(l_dropout);
        out__.write(l_loss);
        out__.write(slr_vec);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> p_recrud =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 11;
      stan::model::assign(p_recrud, stan::math::inv_logit(slr_vec),
        "assigning variable p_recrud");
      out__.write(p_recrud);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ q_mismatch = DUMMY_VAR__;
      current_statement__ = 1;
      q_mismatch = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, q_mismatch);
      local_scalar_t__ q_loss = DUMMY_VAR__;
      current_statement__ = 2;
      q_loss = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, q_loss);
      local_scalar_t__ q_dropout = DUMMY_VAR__;
      current_statement__ = 3;
      q_dropout = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, q_dropout);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> freq =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(J,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(max_K, DUMMY_VAR__));
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
        current_statement__ = 4;
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          current_statement__ = 4;
          stan::model::assign(freq, in__.read<local_scalar_t__>(),
            "assigning variable freq", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_simplex(freq);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "q_mismatch",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "q_loss", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "q_dropout",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "freq", "double",
        std::vector<size_t>{static_cast<size_t>(J),
          static_cast<size_t>(max_K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ q_mismatch = DUMMY_VAR__;
      current_statement__ = 1;
      q_mismatch = context__.vals_r("q_mismatch")[(1 - 1)];
      out__.write_free_lub(0, 1, q_mismatch);
      local_scalar_t__ q_loss = DUMMY_VAR__;
      current_statement__ = 2;
      q_loss = context__.vals_r("q_loss")[(1 - 1)];
      out__.write_free_lub(0, 1, q_loss);
      local_scalar_t__ q_dropout = DUMMY_VAR__;
      current_statement__ = 3;
      q_dropout = context__.vals_r("q_dropout")[(1 - 1)];
      out__.write_free_lub(0, 1, q_dropout);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> freq =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(J,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(max_K, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> freq_flat__;
        current_statement__ = 4;
        freq_flat__ = context__.vals_r("freq");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 4;
            stan::model::assign(freq, freq_flat__[(pos__ - 1)],
              "assigning variable freq", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_simplex(freq);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"q_mismatch", "q_loss", "q_dropout",
                "freq"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"log_freq", "l_match", "l_mismatch", "l_dropout", "l_loss",
             "slr_vec"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"p_recrud"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(J),
                  static_cast<size_t>(max_K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J),
               static_cast<size_t>(max_K)}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "q_mismatch");
    param_names__.emplace_back(std::string() + "q_loss");
    param_names__.emplace_back(std::string() + "q_dropout");
    for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        param_names__.emplace_back(std::string() + "freq" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          param_names__.emplace_back(std::string() + "log_freq" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "l_match");
      param_names__.emplace_back(std::string() + "l_mismatch");
      param_names__.emplace_back(std::string() + "l_dropout");
      param_names__.emplace_back(std::string() + "l_loss");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "slr_vec" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "p_recrud" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "q_mismatch");
    param_names__.emplace_back(std::string() + "q_loss");
    param_names__.emplace_back(std::string() + "q_dropout");
    for (int sym1__ = 1; sym1__ <= (max_K - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        param_names__.emplace_back(std::string() + "freq" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= max_K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          param_names__.emplace_back(std::string() + "log_freq" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      param_names__.emplace_back(std::string() + "l_match");
      param_names__.emplace_back(std::string() + "l_mismatch");
      param_names__.emplace_back(std::string() + "l_dropout");
      param_names__.emplace_back(std::string() + "l_loss");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "slr_vec" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "p_recrud" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"q_mismatch\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"q_loss\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"q_dropout\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"freq\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(max_K) + "}},\"block\":\"parameters\"},{\"name\":\"log_freq\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(max_K) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"l_match\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"l_mismatch\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"l_dropout\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"l_loss\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"slr_vec\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"p_recrud\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"q_mismatch\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"q_loss\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"q_dropout\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"freq\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((max_K -1)) + "}},\"block\":\"parameters\"},{\"name\":\"log_freq\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(max_K) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"l_match\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"l_mismatch\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"l_dropout\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"l_loss\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"slr_vec\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"p_recrud\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + 1) + (J * max_K));
    const size_t num_transformed = emit_transformed_parameters * (((((((J *
      max_K) + 1) + 1) + 1) + 1) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + 1) + 1) + (J * max_K));
    const size_t num_transformed = emit_transformed_parameters * (((((((J *
      max_K) + 1) + 1) + 1) + 1) + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_malrebay_ampseq_model_namespace::model_malrebay_ampseq_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_malrebay_ampseq_model_namespace::profiles__;
}
#endif
#endif
